# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mk56e6PM1A6ZNTTYtES0JxfI61SV4hP4

pip install pycrypto

> Блок с отступами

> Блок с отступами

> Блок с отступами
"""

pip install pycrypto



pip install simple-crypt

import simplecrypt
from simplecrypt import *

import urllib
from urllib import request

encrypted = urllib.request.urlopen('https://stepic.org/media/attachments/lesson/24466/encrypted.bin').read()

passwords = urllib.request.urlopen('https://stepic.org/media/attachments/lesson/24466/passwords.txt').read().strip().split()

print(encrypted)
print(passwords)

for password in passwords:
  try:
    plaintext = decrypt(password, encrypted)
    print(plaintext)
  except:
    print(1)

"""# Новый раздел"""